#!/bin/bash
#
# Merges changes from the upstream without the undesired commits.

set -e

export GIT_EDITOR=true

git switch \
	--detach \
	upstream/main

git rebase \
	--onto 2b1f7cc9ea70119109e9ffd559c27b449ff83546{^,} ||
	true

while true; do
	# Files added by the undesired commits.
	rm -fr \
		LICENSE \
		LICENSES \
		REUSE.toml

	git add -A

	if git rebase --continue; then
		break
	fi
done

git rebase main

git branch \
	--force \
	main \
	HEAD

git switch main
